#!/usr/bin/env python3
"""Inventory oversized handwritten runtime files."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ROOTS = (Path("backend"), Path("frontend/src"))
EXTS = {".py", ".ts", ".vue"}
SKIP = {".git", "node_modules", "dist", "build", ".venv", "__pycache__"}
MIGRATIONS = (Path("backend/alembic/versions"),)
VERIFICATION = (Path("backend/tools"), Path("frontend/scripts"))
LEGACY = (
    Path("frontend/src/views"),
    Path("frontend/src/components"),
    Path("frontend/src/console"),
    Path("frontend/src/layouts"),
)
HIGH_RISK = {
    "backend/handler/roms_handler.py",
    "backend/handler/metadata/igdb.py",
    "backend/handler/scan_handler.py",
    "backend/endpoints/roms/__init__.py",
    "backend/endpoints/storage.py",
    "backend/handler/database/legacy_migration_handler.py",
    "backend/endpoints/sockets/scan.py",
    "frontend/src/v2/views/Scan.vue",
}


@dataclass(frozen=True)
class Entry:
    path: str
    count: int
    kind: str
    decision: str
    risk: str


def logical_lines(path: Path) -> int:
    count = 0
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if line and not line.startswith(("#", "//", "/*", "*", "*/")):
            count += 1
    return count


def is_under(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def classify(path: Path) -> tuple[str, str, str]:
    rel = path.as_posix()
    if "__generated__" in rel or ".generated." in path.name:
        return "generated", "exempt: generated output", "excluded"
    if any(is_under(path, marker) for marker in MIGRATIONS):
        return "migration", "exempt: migration history", "excluded"
    if (
        "/tests/" in f"/{rel}/"
        or "/test/" in f"/{rel}/"
        or "/fixtures/" in f"/{rel}/"
        or path.name.endswith(("_test.py", ".test.ts"))
    ):
        return "fixture/test", "exempt: test or fixture support", "excluded"
    if any(is_under(path, marker) for marker in VERIFICATION):
        return "verification tool", "exempt: verification/developer tool", "excluded"
    if any(is_under(path, marker) for marker in LEGACY):
        return (
            "legacy runtime",
            "document owner and boundary before extraction",
            "defer unless characterization coverage exists",
        )
    if rel in HIGH_RISK or rel.startswith("frontend/src/v2/"):
        return (
            "new runtime",
            "document boundary; extract only one tested responsibility",
            "defer pending focused parity coverage",
        )
    return (
        "new runtime",
        "review ownership and callers before extraction",
        "defer pending focused parity coverage",
    )


def entries(threshold: int) -> list[Entry]:
    found = []
    for base in ROOTS:
        target = ROOT / base
        if not target.exists():
            continue
        for path in target.rglob("*"):
            if (
                not path.is_file()
                or path.suffix not in EXTS
                or any(part in SKIP for part in path.parts)
            ):
                continue
            count = logical_lines(path)
            if count <= threshold:
                continue
            rel = path.relative_to(ROOT)
            kind, decision, risk = classify(rel)
            found.append(Entry(rel.as_posix(), count, kind, decision, risk))
    return sorted(found, key=lambda item: (-item.count, item.path))


def render(threshold: int) -> str:
    all_entries = entries(threshold)
    high = [item for item in all_entries if item.count > 1000]
    runtime = [
        item for item in all_entries if item.kind in {"legacy runtime", "new runtime"}
    ]
    exempt = [
        item
        for item in all_entries
        if item.kind not in {"legacy runtime", "new runtime"}
    ]
    out = [
        "# Phase 24 Plan 12 oversized runtime audit",
        "",
        "Generated by backend/tools/check_file_sizes.py.",
        "",
        "## Method",
        "",
        "- Scope: handwritten Python under backend/ and TypeScript/Vue under frontend/src/.",
        "- Count: non-blank, non-comment logical source lines, not physical file lines.",
        "- Files over 500 require an explicit decision. Files over 1,000 are high-risk.",
        "- Generated files, migrations, fixtures/tests, and verification tools are classified and exempt from extraction targets.",
        "",
        "## Summary",
        "",
        f"- Files over 500 logical lines: **{len(all_entries)}**",
        f"- Files over 1,000 logical lines: **{len(high)}**",
        f"- Runtime candidates over 500: **{len(runtime)}**",
        f"- Exempt oversized files: **{len(exempt)}**",
        "",
        "## Files over 1,000 logical lines",
        "",
        "| Logical lines | Classification | Risk | Decision | File |",
        "| ---: | --- | --- | --- | --- |",
    ]
    out += [
        f"| {item.count} | {item.kind} | {item.risk} | {item.decision} | {item.path} |"
        for item in high
    ] or ["| - | - | - | None | - |"]
    out += [
        "",
        "## Files over 500 logical lines",
        "",
        "| Logical lines | Classification | Risk | Decision | File |",
        "| ---: | --- | --- | --- | --- |",
    ]
    out += [
        f"| {item.count} | {item.kind} | {item.risk} | {item.decision} | {item.path} |"
        for item in all_entries
    ] or ["| - | - | - | None | - |"]
    out += [
        "",
        "## Explicit high-risk notes",
        "",
        "- No legacy handler, generated file, migration, fixture, or verification tool is split solely to reduce a line count.",
        "- Storage mapping, PC/DLC, provider, lifecycle, and ownership responsibilities remain owned by existing modules.",
        "- Any future extraction must add characterization/parity coverage before moving one cohesive responsibility.",
        "- This plan documents oversized runtime risks first. Extraction is deferred where existing focused tests do not clearly establish a safe seam.",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--runtime", action="store_true")
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--threshold", type=int, default=500)
    args = parser.parse_args()
    if not args.runtime:
        parser.error("--runtime is required")
    report = args.report if args.report.is_absolute() else ROOT / args.report
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(render(args.threshold), encoding="utf-8")
    found = entries(args.threshold)
    print(f"wrote {report.relative_to(ROOT)}")
    print(f"files over {args.threshold}: {len(found)}")
    print(f"files over 1000: {sum(item.count > 1000 for item in found)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
